#%RAML 0.8
title: Payment system
version: 1.0
documentation:
- title: Payment system
  content: |
    # Introduction

    What does your API do?


    # Overview

    Things that the developers should know about


    # Authentication

    What is the preferred way of using the API?


    # Error Codes

    What errors and status codes can a user expect?


    # Rate limit

    Is there a limit to the number of requests an user can send?
baseUri: https://payment.checksystem.biz
baseUriParameters: {}
/registerUser:
  get:
    description: ''
    responses: {}
    queryParameters:
      Id_Terminal:
        description: ''
        type: integer
        example: 1234
        default: ''
        required: true
        displayName: Id_Terminal
      Id_Group:
        description: ''
        type: integer
        example: 1
        default: ''
        required: true
        displayName: Id_Group
/queryUser:
  get:
    description: ''
    responses: {}
    queryParameters:
      Id_Terminal:
        description: ''
        type: integer
        example: 1234
        default: ''
        required: true
        displayName: Id_Terminal
      Customer:
        description: ''
        type: integer
        example: ''
        default: ''
        required: true
        displayName: Customer
      Password:
        description: ''
        type: integer
        example: 8401
        default: ''
        required: true
        displayName: Password
/querySystemStatus:
  get:
    description: ''
    responses: {}
    queryParameters:
      Id_Terminal:
        description: ''
        type: integer
        example: 1234
        default: ''
        required: true
        displayName: Id_Terminal
/registerPayment:
  get:
    description: ''
    responses: {}
    queryParameters:
      transactionID:
        description: ''
        type: string
        example: 4bfd5bad-8261-4d56-a46e-3b16b2132ff4
        default: ''
        required: true
        displayName: transactionID
      Id_Terminal:
        description: ''
        type: integer
        example: 1234
        default: ''
        required: true
        displayName: Id_Terminal
      Customer:
        description: ''
        type: integer
        example: ''
        default: ''
        required: true
        displayName: Customer
      Password:
        description: ''
        type: integer
        example: 8401
        default: ''
        required: true
        displayName: Password
      Amount:
        description: ''
        type: number
        example: 100.00
        default: ''
        required: true
        displayName: Amount
/registerPayoutBegin:
  get:
    description: ''
    responses: {}
    queryParameters:
      transactionID:
        description: ''
        type: string
        example: e271a37e-f0d8-482d-9cbb-16cd78a17e7d
        default: ''
        required: true
        displayName: transactionID
      Id_Terminal:
        description: ''
        type: integer
        example: 1234
        default: ''
        required: true
        displayName: Id_Terminal
      Customer:
        description: ''
        type: integer
        example: ''
        default: ''
        required: true
        displayName: Customer
      Password:
        description: ''
        type: integer
        example: 8401
        default: ''
        required: true
        displayName: Password
      Amount:
        description: ''
        type: number
        example: 100.00
        default: ''
        required: true
        displayName: Amount
/registerPayoutEnd:
  get:
    description: ''
    responses: {}
    queryParameters:
      transactionID:
        description: ''
        type: string
        example: 2558e931-655b-4428-8c0c-68d5b7b59743
        default: ''
        required: true
        displayName: transactionID
      BeginTransactionID:
        description: ''
        type: string
        example: undefined
        default: ''
        required: true
        displayName: BeginTransactionID
      Id_Terminal:
        description: ''
        type: integer
        example: 1234
        default: ''
        required: true
        displayName: Id_Terminal
      Customer:
        description: ''
        type: integer
        example: ''
        default: ''
        required: true
        displayName: Customer
      Password:
        description: ''
        type: integer
        example: 8401
        default: ''
        required: true
        displayName: Password
      dispenseStatus:
        description: ''
        type: string
        example: successful
        default: ''
        required: true
        displayName: dispenseStatus
      Amount:
        description: ''
        type: number
        example: 100.00
        default: ''
        required: true
        displayName: Amount
      WithdrawalAmount:
        description: ''
        type: number
        example: 100.00
        default: ''
        required: true
        displayName: WithdrawalAmount
