#%RAML 0.8
title: Payment system
version: 1.0
documentation:
- title: Payment system
  content: |
    # Introduction

    What does your API do?


    # Overview

    Things that the developers should know about


    # Authentication

    What is the preferred way of using the API?


    # Error Codes

    What errors and status codes can a user expect?


    # Rate limit

    Is there a limit to the number of requests an user can send?
baseUri: https://payment.checksystem.biz
protocols:
- HTTPS
baseUriParameters: {}
/registerUser:
  get:
    responses:
      200:
        description: Success
    queryParameters:
      Id_Terminal:
        type: integer
        example: 1234
        required: true
        displayName: Id_Terminal
      Id_Group:
        type: integer
        example: 1
        required: true
        displayName: Id_Group
/queryUser:
  get:
    responses:
      200:
        description: Success
    queryParameters:
      Id_Terminal:
        type: integer
        example: 1234
        required: true
        displayName: Id_Terminal
      Customer:
        type: string
        example: 0000000168
        required: true
        displayName: Customer
      Password:
        type: integer
        example: 8401
        required: true
        displayName: Password
/querySystemStatus:
  get:
    responses:
      200:
        description: Success
    queryParameters:
      Id_Terminal:
        type: integer
        example: 1234
        required: true
        displayName: Id_Terminal
/registerPayment:
  get:
    responses:
      200:
        description: Success
    queryParameters:
      transactionID:
        type: string
        example: 786d55d2-6419-4a05-9cb4-a60e2c1a1a93
        required: true
        displayName: transactionID
      Id_Terminal:
        type: integer
        example: 1234
        required: true
        displayName: Id_Terminal
      Customer:
        type: string
        example: 0000000168
        required: true
        displayName: Customer
      Password:
        type: integer
        example: 8401
        required: true
        displayName: Password
      Amount:
        type: number
        example: 100.00
        required: true
        displayName: Amount
/registerPayoutBegin:
  get:
    responses:
      200:
        description: Success
    queryParameters:
      transactionID:
        type: string
        example: 802c9ecd-c781-4aa5-bf5d-2e93338a8b83
        required: true
        displayName: transactionID
      Id_Terminal:
        type: integer
        example: 1234
        required: true
        displayName: Id_Terminal
      Customer:
        type: string
        example: 0000000168
        required: true
        displayName: Customer
      Password:
        type: integer
        example: 8401
        required: true
        displayName: Password
      Amount:
        type: number
        example: 100.00
        required: true
        displayName: Amount
/registerPayoutEnd:
  get:
    responses:
      200:
        description: Success
    queryParameters:
      transactionID:
        type: string
        example: 487740f4-d1e8-4c41-85cc-b931bb501391
        required: true
        displayName: transactionID
      BeginTransactionID:
        type: string
        example: undefined
        required: true
        displayName: BeginTransactionID
      Id_Terminal:
        type: integer
        example: 1234
        required: true
        displayName: Id_Terminal
      Customer:
        type: string
        example: 0000000168
        required: true
        displayName: Customer
      Password:
        type: integer
        example: 8401
        required: true
        displayName: Password
      dispenseStatus:
        type: string
        example: successful
        required: true
        displayName: dispenseStatus
      Amount:
        type: number
        example: 100.00
        required: true
        displayName: Amount
      WithdrawalAmount:
        type: number
        example: 100.00
        required: true
        displayName: WithdrawalAmount
