#%RAML 0.8
title: Payment system
version: 1.0
documentation:
- title: Payment system
  content: 'TODO: Add Description'
baseUri: http://example.com
baseUriParameters: {}
/registerUser:
  get:
    description: 'TODO: Add Description'
    responses: {}
    queryParameters:
      Id_Terminal:
        description: ''
        type: string
        example: '{{terminal}}'
        default: ''
        required: true
        displayName: Id_Terminal
      Id_Group:
        description: ''
        type: string
        example: '{{groupid}}'
        default: ''
        required: true
        displayName: Id_Group
/queryUser:
  get:
    description: 'TODO: Add Description'
    responses: {}
    queryParameters:
      Id_Terminal:
        description: ''
        type: string
        example: '{{terminal}}'
        default: ''
        required: true
        displayName: Id_Terminal
      Customer:
        description: ''
        type: string
        example: '{{user}}'
        default: ''
        required: true
        displayName: Customer
      Password:
        description: ''
        type: string
        example: '{{password}}'
        default: ''
        required: true
        displayName: Password
/querySystemStatus:
  get:
    description: 'TODO: Add Description'
    responses: {}
    queryParameters:
      Id_Terminal:
        description: ''
        type: string
        example: '{{terminal}}'
        default: ''
        required: true
        displayName: Id_Terminal
/queryUserAndAgent:
  get:
    description: 'TODO: Add Description'
    responses: {}
    queryParameters:
      Id_Terminal:
        description: ''
        type: string
        example: '{{terminal}}'
        default: ''
        required: true
        displayName: Id_Terminal
      Customer:
        description: ''
        type: string
        example: '{{user}}'
        default: ''
        required: true
        displayName: Customer
      Password:
        description: ''
        type: string
        example: '{{password}}'
        default: ''
        required: true
        displayName: Password
/registerPayment:
  get:
    description: 'TODO: Add Description'
    responses: {}
    queryParameters:
      transactionID:
        description: ''
        type: string
        example: 33d304a6-92d8-4c9d-b078-83f02cd7de00
        default: ''
        required: true
        displayName: transactionID
      Id_Terminal:
        description: ''
        type: string
        example: '{{terminal}}'
        default: ''
        required: true
        displayName: Id_Terminal
      Customer:
        description: ''
        type: string
        example: '{{user}}'
        default: ''
        required: true
        displayName: Customer
      Password:
        description: ''
        type: string
        example: '{{password}}'
        default: ''
        required: true
        displayName: Password
      Amount:
        description: ''
        type: string
        example: '{{amount}}'
        default: ''
        required: true
        displayName: Amount
/registerPayoutBegin:
  get:
    description: 'TODO: Add Description'
    responses: {}
    queryParameters:
      transactionID:
        description: ''
        type: string
        example: 9eba3625-5a45-4bff-89ed-7715d1762470
        default: ''
        required: true
        displayName: transactionID
      Id_Terminal:
        description: ''
        type: string
        example: '{{terminal}}'
        default: ''
        required: true
        displayName: Id_Terminal
      Customer:
        description: ''
        type: string
        example: '{{user}}'
        default: ''
        required: true
        displayName: Customer
      Password:
        description: ''
        type: string
        example: '{{password}}'
        default: ''
        required: true
        displayName: Password
      Amount:
        description: ''
        type: string
        example: '{{amount}}'
        default: ''
        required: true
        displayName: Amount
/registerPayoutEnd:
  get:
    description: 'TODO: Add Description'
    responses: {}
    queryParameters:
      transactionID:
        description: ''
        type: string
        example: b66842f6-a557-4dfe-b8e1-8b70b5be6d88
        default: ''
        required: true
        displayName: transactionID
      BeginTransactionID:
        description: ''
        type: string
        example: '{{last_registerPayoutBeginTrID}}'
        default: ''
        required: true
        displayName: BeginTransactionID
      Id_Terminal:
        description: ''
        type: string
        example: '{{terminal}}'
        default: ''
        required: true
        displayName: Id_Terminal
      Customer:
        description: ''
        type: string
        example: '{{user}}'
        default: ''
        required: true
        displayName: Customer
      Password:
        description: ''
        type: string
        example: '{{password}}'
        default: ''
        required: true
        displayName: Password
      dispenseStatus:
        description: ''
        type: string
        example: successful
        default: ''
        required: true
        displayName: dispenseStatus
      Amount:
        description: ''
        type: string
        example: '{{amount}}'
        default: ''
        required: true
        displayName: Amount
      WithdrawalAmount:
        description: ''
        type: string
        example: '{{amount}}'
        default: ''
        required: true
        displayName: WithdrawalAmount
